[build]
  command = "next build "
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18.20.2"

[ignore]
  command = "git diff --quiet $CACHED_COMMIT_REF..HEAD backend/ || exit 1"