name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check formatting
      run: npm run frontend:format:check
      
    - name: Run linting
      run: npm run frontend:lint
      
    - name: Run frontend tests
      run: npm run frontend:test
      
    # Uncomment when backend is ready
    # - name: Run backend tests
    #   run: npm run backend:test 