name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Cache dependencies and Next.js build
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/frontend/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Check formatting
        working-directory: frontend
        run: npm run format:check

      - name: Run linting
        working-directory: frontend
        run: npm run lint

      - name: Run frontend tests
        working-directory: frontend
        run: npm test

      # Uncomment when backend is ready
      # - name: Run backend tests
      #   working-directory: backend
      #   run: npm run backend:test

      - name: Set up Sentry CLI
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Create Sentry Release for Backuend
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'  # Only run on push to master
        working-directory: backend
        run: |
          export SENTRY_ORG=your-org-slug
          export SENTRY_PROJECT=your-project-slug
          sentry-cli releases new "1.0.0"
          sentry-cli releases set-commits "1.0.0" --auto
          sentry-cli releases finalize "1.0.0"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}